Repository depromeet/gryffindor, pull requests merged in 2025-09, with the labels that each got.

#2 feat: add slack notifications for pr review
  .github/CODEOWNERS
  .github/reviewers.json
  .github/workflows/slack-pull-request-comment.yml
  .github/workflows/slack-pull-request.yml
Labels: ⚙️ setting

#13 feat: core layout system with guide
  .claude/settings.local.json
  .github/reviewers.json
  .gitignore
  .husky/pre-commit
  COMPONENT_USAGE.md
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(main)/home/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/map/page.tsx
  src/app/(stack)/item/page.tsx
  src/app/(stack)/layout.tsx
  src/app/(stack)/mypage/[...id]/page.tsx
  src/app/(stack)/mypage/page.tsx
  src/app/(stack)/mypage/tester/page.tsx
  src/app/_providers/QueryProvider.tsx
  src/app/_providers/SsgoiProvider.tsx
  src/app/_providers/index.ts
  src/app/auth/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/shared/config/index.ts
  src/shared/config/routeConfig.ts
  src/shared/config/transitions.ts
  src/shared/lib/.gitkeep
  src/shared/lib/hooks/useMobile.ts
  src/shared/lib/index.ts
  src/shared/lib/utils.ts
  src/shared/ui/.gitkeep
  src/shared/ui/FloatingNavButton.tsx
  src/shared/ui/Icon.tsx
  src/shared/ui/StackHeader.tsx
  src/shared/ui/TransitionLayout.tsx
  src/shared/ui/icons/HomeIcon.tsx
  src/shared/ui/icons/MapIcon.tsx
  src/shared/ui/icons/UserIcon.tsx
  src/shared/ui/icons/index.ts
  src/shared/ui/index.ts
Labels: ✨ feature, ⚙️ setting

#27 feat: implement bottom sheet
  src/app/(main)/map/page.tsx
  src/app/_providers/BottomSheetProvider.tsx
  src/app/_providers/index.ts
  src/features/filter/ui/Filter.tsx
  src/shared/lib/hooks/index.ts
  src/shared/lib/hooks/useBottomSheet.ts
  src/shared/ui/BottomSheet.tsx
  src/shared/ui/index.ts
Labels: ✨ feature, 🎨 design

#31 feat: implement map page componets
  src/app/globals.css
  src/entities/map/api/.gitkeep
  src/entities/map/lib/.gitkeep
  src/entities/map/model/.gitkeep
  src/entities/map/ui/MapBubble.tsx
  src/entities/map/ui/MapLocation.tsx
  src/entities/map/ui/MapPin.tsx
  src/entities/map/ui/index.ts
  src/features/map/api/.gitkeep
  src/features/map/lib/.gitkeep
  src/features/map/model/.gitkeep
  src/features/map/ui/MapFloatingButton.tsx
  src/features/map/ui/MapRefreshButton.tsx
  src/features/map/ui/index.ts
  src/shared/ui/icons/crown.svg
  src/shared/ui/icons/down-triangle.svg
  src/shared/ui/icons/filter.svg
  src/shared/ui/icons/index.ts
  src/shared/ui/icons/map-bubble.svg
  src/shared/ui/icons/refresh.svg
  src/shared/ui/icons/target.svg
Labels: ✨ feature, 🎨 design

#30 feat: store detail publishing
  src/app/(stack)/store/[id]/page.tsx
  src/app/globals.css
  src/entities/review/api/mock.ts
  src/entities/review/model/constants.ts
  src/entities/review/model/index.ts
  src/entities/review/model/types.ts
  src/entities/review/ui/ReviewCard.tsx
  src/entities/review/ui/index.ts
  src/entities/store/model/constant.ts
  src/entities/store/model/index.ts
  src/entities/store/model/types.ts
  src/entities/store/ui/MenuItem.tsx
  src/entities/store/ui/index.ts
  src/features/store/ui/ReviewList.tsx
  src/features/store/ui/ReviewSection.tsx
  src/features/store/ui/SeatImageGallery.tsx
  src/features/store/ui/SeatInfoSection.tsx
  src/features/store/ui/StoreInfo.tsx
  src/features/store/ui/SuggestionCard.tsx
  src/features/store/ui/index.ts
  src/shared/config/routeConfig.ts
  src/shared/lib/hooks/useInfiniteScroll.ts
  src/shared/lib/index.ts
  src/shared/lib/utils/formatDateUtils.ts
  src/shared/ui/ChipFilter.tsx
  src/shared/ui/StackHeader.tsx
  src/shared/ui/TextButton.tsx
  src/shared/ui/TransitionLayout.tsx
  src/shared/ui/icons/call.svg
  src/shared/ui/icons/character.svg
  src/shared/ui/icons/down-arrow.svg
  src/shared/ui/icons/index.ts
  src/shared/ui/icons/kebab.svg
  src/shared/ui/icons/location.svg
Labels: ✨ feature

#39 feat: store detail api connect
  src/app/(stack)/store/[id]/page.tsx
  src/entities/review/ui/ReviewCard.tsx
  src/entities/store/model/constant.ts
  src/entities/store/model/index.ts
  src/entities/store/model/types.ts
  src/entities/store/ui/MenuItem.tsx
  src/features/store/api/.gitkeep
  src/features/store/api/getStoreDetail.ts
  src/features/store/api/index.ts
  src/features/store/ui/SeatImageGallery.tsx
  src/features/store/ui/SeatInfoSection.tsx
  src/features/store/ui/StoreInfo.tsx
  src/features/store/ui/SuggestionCard.tsx
  src/shared/api/queryKeys.ts
  src/shared/config/constants.ts
  src/shared/ui/TextButton.tsx
  src/shared/ui/icons/bar-seat.svg
  src/shared/ui/icons/bulkhead.svg
  src/shared/ui/icons/for-four.svg
  src/shared/ui/icons/for-one.svg
  src/shared/ui/icons/for-two.svg
  src/shared/ui/icons/index.ts
Labels: ✨ feature

#43 feat: add nickname modifiy page
  docs/COMPONENT_USAGE.md
  src/app/(stack)/mypage/nickname/page.tsx
  src/entities/honbob/index.ts
  src/entities/honbob/lib/util/pickHonbabLevelIcon.ts
  src/entities/honbob/model/constant.ts
  src/entities/honbob/ui/HonbobCarouselSlide.tsx
  src/entities/honbob/ui/HonbobLevelCard.tsx
  src/entities/honbob/ui/HonbobLevelInfoCard.tsx
  src/entities/honbob/ui/HonbobLevelTestGuideModal.tsx
  src/entities/user/ui/UserMenuList.tsx
  src/entities/user/ui/UserProfileInfo.tsx
  src/features/auth/ui/LogoutConfirmModal.tsx
  src/features/auth/ui/index.ts
  src/features/user/lib/hooks/useMutateUserNickName.ts
  src/features/user/lib/index.ts
  src/features/user/ui/AccountActionsSection.tsx
  src/features/user/ui/UserNicknameModifySection.tsx
  src/features/user/ui/UserProfileSection.tsx
  src/features/user/ui/index.ts
  src/shared/api/queryKeys.ts
  src/shared/config/index.ts
  src/shared/config/inputConfig.ts
  src/shared/config/routeConfig.ts
  src/shared/lib/assets/index.ts
  src/shared/lib/assets/png/character/basic.png
  src/shared/lib/assets/png/character/sad.png
  src/shared/lib/assets/png/onBoarding/Lv.1.png
  src/shared/lib/assets/png/onBoarding/Lv.2.png
  src/shared/lib/assets/png/onBoarding/Lv.3.png
  src/shared/lib/assets/png/onBoarding/Lv.4.png
  src/shared/lib/hooks/useInputField.ts
  src/shared/lib/index.ts
  src/shared/lib/utils/deriveUserState.ts
  src/shared/lib/utils/inputValidation.ts
  src/shared/model/types.ts
  src/shared/ui/Input.tsx
  src/shared/ui/MainHeader.tsx
  src/shared/ui/Select.tsx
  src/shared/ui/StationOverlaySelect.tsx
  src/shared/ui/index.ts
Labels: 📄 docs, ✨ feature, 🎨 design

#47 feat: nickname patch get store api
  next.config.ts
  src/auth.ts
  src/entities/storeList/api/index.ts
  src/entities/storeList/api/storeListApi.ts
  src/entities/storeList/api/types.ts
  src/entities/storeList/lib/.gitkeep
  src/entities/storeList/lib/index.ts
  src/entities/storeList/lib/utils/getDefaultStationCenter.ts
  src/entities/storeList/model/mocks.ts
  src/entities/storeList/ui/SelectedStoreCard.tsx
  src/entities/storeList/ui/StoreCard.tsx
  src/entities/storeList/ui/StoreLevelList.tsx
  src/entities/storeList/ui/StoreList.tsx
  src/features/store/ui/SeatInfoSection.tsx
  src/features/user/ui/UserNicknameModifySection.tsx
  src/shared/api/queryKeys.ts
  src/shared/lib/hooks/useSessionStorage.ts
  src/shared/store/index.ts
  src/shared/store/locationStore.ts
  src/shared/ui/StationOverlaySelect.tsx
Labels: ✨ feature

#48 refactor: imporve map page structure
  src/app/(main)/map/page.tsx
  src/auth.ts
  src/entities/honbob/ui/HonbobLevelTestGuideModal.tsx
  src/entities/map/ui/MapBubble.tsx
  src/entities/map/ui/MapPin.tsx
  src/entities/map/ui/index.ts
  src/entities/storeList/api/types.ts
  src/entities/storeList/model/index.ts
  src/entities/storeList/model/mockData.ts
  src/entities/storeList/ui/SelectedStoreCard.tsx
  src/entities/user/ui/UserMenuList.tsx
  src/features/auth/ui/LogoutConfirmModal.tsx
  src/features/map/lib/.gitkeep
  src/features/map/lib/hooks/useMapMarkers.ts
  src/features/map/lib/index.ts
  src/features/map/model/.gitkeep
  src/features/map/model/index.ts
  src/features/map/model/store.ts
  src/features/map/ui/FetchStoreListButton.tsx
  src/features/map/ui/FilterBottomSheet.tsx
  src/features/map/ui/MapActionButton.tsx
  src/features/map/ui/MapFloatingButton.tsx
  src/features/map/ui/MapMarkers.tsx
  src/features/map/ui/MapView.tsx
  src/features/map/ui/NaverMap.tsx
  src/features/map/ui/StoreBottomSheet.tsx
  src/features/map/ui/index.ts
  src/shared/ui/icons/bubble-pick.svg
  src/shared/ui/icons/bubble.svg
  src/shared/ui/icons/index.ts
  src/shared/ui/icons/target.svg
  src/shared/ui/index.ts
Labels: 🛠️ refactor

#52 feat: integrate map api
  src/app/(main)/map/page.tsx
  src/entities/storeList/api/types.ts
  src/entities/storeList/model/mockData.ts
  src/entities/storeList/ui/SelectedStoreCard.tsx
  src/features/filter/model/types.ts
  src/features/filter/ui/Filter.tsx
  src/features/filter/utils/filter.ts
  src/features/map/lib/hooks/useMapMarkers.ts
  src/features/map/lib/hooks/useStoreListQuery.ts
  src/features/map/lib/index.ts
  src/features/map/ui/MapMarkers.tsx
  src/features/map/ui/MapView.tsx
  src/features/map/ui/StoreBottomSheet.tsx
  src/shared/api/queryKeys.ts
  src/shared/lib/hooks/useBottomSheet.ts
  src/shared/ui/BottomSheet.tsx
Labels: ✨ feature

#51 design: add ReportStore component
  src/app/(main)/home/page.tsx
  src/entities/honbob/ui/HonbobLevelCard.tsx
  src/entities/store/ui/ReportStore.tsx
  src/entities/store/ui/index.ts
  src/entities/user/ui/WelcomeUser.tsx
  src/shared/ui/icons/color-right-chevron.svg
  src/shared/ui/icons/index.ts
Labels: 🎨 design

#54 fix: design qa
  src/app/(main)/map/page.tsx
  src/entities/review/ui/ReviewCard.tsx
  src/entities/storeList/ui/SelectedStoreCard.tsx
  src/features/filter/ui/Filter.tsx
  src/features/map/ui/FetchStoreListButton.tsx
  src/features/map/ui/StoreBottomSheet.tsx
  src/features/store/ui/SuggestionCard.tsx
  src/shared/lib/assets/png/character/edit.png
  src/shared/ui/BottomSheet.tsx
Labels: 🎨 design
